// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4XsPilWlwHcExHpKQUAFeMFVdZWoUZ4c',
    appId: '1:460041179769:web:3828f8d0943c83fa61faa8',
    messagingSenderId: '460041179769',
    projectId: 'flutter-login-866f8',
    authDomain: 'flutter-login-866f8.firebaseapp.com',
    storageBucket: 'flutter-login-866f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcguc9ErxoDnNvw7WJuCfLcYWILU2N_rA',
    appId: '1:460041179769:android:42b7b2e6b758849461faa8',
    messagingSenderId: '460041179769',
    projectId: 'flutter-login-866f8',
    storageBucket: 'flutter-login-866f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfo3bsi20Y7ZCX7TqtGz_4TyIWIBKziqY',
    appId: '1:460041179769:ios:8ef4c512c1502ea861faa8',
    messagingSenderId: '460041179769',
    projectId: 'flutter-login-866f8',
    storageBucket: 'flutter-login-866f8.firebasestorage.app',
    androidClientId: '460041179769-13h586lddpskv85oqpvaphuaibhp3knn.apps.googleusercontent.com',
    iosClientId: '460041179769-pqhem1vdl4hev3lqtc24qfqibum4g493.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfo3bsi20Y7ZCX7TqtGz_4TyIWIBKziqY',
    appId: '1:460041179769:ios:8ef4c512c1502ea861faa8',
    messagingSenderId: '460041179769',
    projectId: 'flutter-login-866f8',
    storageBucket: 'flutter-login-866f8.firebasestorage.app',
    androidClientId: '460041179769-13h586lddpskv85oqpvaphuaibhp3knn.apps.googleusercontent.com',
    iosClientId: '460041179769-pqhem1vdl4hev3lqtc24qfqibum4g493.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginGoogle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4XsPilWlwHcExHpKQUAFeMFVdZWoUZ4c',
    appId: '1:460041179769:web:911291d919ff461f61faa8',
    messagingSenderId: '460041179769',
    projectId: 'flutter-login-866f8',
    authDomain: 'flutter-login-866f8.firebaseapp.com',
    storageBucket: 'flutter-login-866f8.firebasestorage.app',
  );

}